// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID               pgtype.UUID        `json:"id"`
	Filename         string             `json:"filename"`
	MimeType         string             `json:"mime_type"`
	StoragePath      string             `json:"storage_path"`
	Original         []byte             `json:"original"`
	SourceMarkdown   string             `json:"source_markdown"`
	Status           string             `json:"status"`
	ChunkSize        int32              `json:"chunk_size"`
	Revision         int32              `json:"revision"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Metadata         []byte             `json:"metadata"`
	MetadataRevision int32              `json:"metadata_revision"`
}

type DocumentChunk struct {
	ID                      pgtype.UUID        `json:"id"`
	DocumentID              pgtype.UUID        `json:"document_id"`
	ChunkIndex              int32              `json:"chunk_index"`
	Content                 string             `json:"content"`
	RawMarkdown             string             `json:"raw_markdown"`
	Breadcrumbs             []byte             `json:"breadcrumbs"`
	TokenCount              int32              `json:"token_count"`
	IsReviewed              bool               `json:"is_reviewed"`
	IsExcluded              bool               `json:"is_excluded"`
	IsDirty                 bool               `json:"is_dirty"`
	QdrantPointID           pgtype.UUID        `json:"qdrant_point_id"`
	Metadata                []byte             `json:"metadata"`
	SourceStart             int32              `json:"source_start"`
	SourceEnd               int32              `json:"source_end"`
	Revision                int32              `json:"revision"`
	IndexedRevision         int32              `json:"indexed_revision"`
	IndexedContent          string             `json:"indexed_content"`
	IndexedModel            string             `json:"indexed_model"`
	IndexedBreadcrumbs      []byte             `json:"indexed_breadcrumbs"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	IndexedDocumentMetadata []byte             `json:"indexed_document_metadata"`
}

type IndexingJob struct {
	ID        pgtype.UUID        `json:"id"`
	Kind      string             `json:"kind"`
	Status    string             `json:"status"`
	Total     int32              `json:"total"`
	Completed int32              `json:"completed"`
	Error     string             `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type IndexingTask struct {
	ID               int64              `json:"id"`
	JobID            pgtype.UUID        `json:"job_id"`
	DocumentID       pgtype.UUID        `json:"document_id"`
	ChunkID          pgtype.UUID        `json:"chunk_id"`
	Kind             string             `json:"kind"`
	Collection       string             `json:"collection"`
	Attempts         int32              `json:"attempts"`
	Done             bool               `json:"done"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	DocumentMetadata []byte             `json:"document_metadata"`
}

type MetadataJob struct {
	DocumentID   pgtype.UUID        `json:"document_id"`
	Status       string             `json:"status"`
	Model        string             `json:"model"`
	BaseRevision int32              `json:"base_revision"`
	Attempts     int32              `json:"attempts"`
	Error        string             `json:"error"`
	Sampled      bool               `json:"sampled"`
	Result       []byte             `json:"result"`
	RunToken     pgtype.UUID        `json:"run_token"`
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
