// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const publishedChunks = `-- name: PublishedChunks :many
SELECT id, document_id, indexed_content, indexed_breadcrumbs, indexed_revision, indexed_document_metadata
FROM document_chunks
WHERE indexed_revision > 0 AND NOT is_excluded
ORDER BY document_id, chunk_index
`

type PublishedChunksRow struct {
	ID                      pgtype.UUID `json:"id"`
	DocumentID              pgtype.UUID `json:"document_id"`
	IndexedContent          string      `json:"indexed_content"`
	IndexedBreadcrumbs      []byte      `json:"indexed_breadcrumbs"`
	IndexedRevision         int32       `json:"indexed_revision"`
	IndexedDocumentMetadata []byte      `json:"indexed_document_metadata"`
}

func (q *Queries) PublishedChunks(ctx context.Context) ([]PublishedChunksRow, error) {
	rows, err := q.db.Query(ctx, publishedChunks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishedChunksRow
	for rows.Next() {
		var i PublishedChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.IndexedContent,
			&i.IndexedBreadcrumbs,
			&i.IndexedRevision,
			&i.IndexedDocumentMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeExpiredSessions)
	return err
}
